# Nixpacks configuration for Railway deployment
# Builds both frontend and backend

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "gcc", "nodejs-18_x"]

[phases.install]
cmds = [
    # Build frontend first
    "cd frontend && npm install && npm run build && cd ..",
    # Then install backend dependencies
    "python -m venv /opt/venv",
    ". /opt/venv/bin/activate && cd backend && pip install -r requirements.txt"
]

[start]
cmd = ". /opt/venv/bin/activate && cd backend && uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8000}"