# Nixpacks configuration for Railway deployment
# Using python311Packages.pip to ensure pip is available

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "gcc"]

[phases.install]
cmds = [
    "python -m venv /opt/venv",
    ". /opt/venv/bin/activate && cd backend && pip install -r requirements.txt"
]

[start]
cmd = ". /opt/venv/bin/activate && cd backend && uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8000}"