# Railway configuration for Backend API Service
# This service handles all API requests and database connections

[build]
builder = "nixpacks"

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "gcc", "postgresql"]

[phases.install]
cmds = [
    "python -m venv /opt/venv",
    ". /opt/venv/bin/activate && pip install --upgrade pip",
    ". /opt/venv/bin/activate && pip install -r backend/requirements.txt"
]

[phases.build]
cmds = [
    # Run any database migrations if needed
    "echo 'Build phase completed'"
]

[deploy]
startCommand = ". /opt/venv/bin/activate && cd backend && uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8000}"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3

[variables]
SERVICE_TYPE = "backend"
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"