# Railway configuration for Frontend Service
# This service builds and serves the React application

[build]
builder = "nixpacks"

[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = [
    "cd frontend && npm ci --production=false"
]

[phases.build]
cmds = [
    "cd frontend && npm run build",
    # Install serve globally for production serving
    "npm install -g serve"
]

[deploy]
startCommand = "serve -s frontend/dist -l ${PORT:-3000} --no-clipboard"
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3

[variables]
SERVICE_TYPE = "frontend"
NODE_ENV = "production"